### ISSUE TITLE
Add Contributors List in index.html

### ISSUE THREAD

**Issue by kd1729** [primeTanM/Excuser#17]
https://github.com/primeTanM/Excuser/graphs/contributors

Create a contributor list below the image in the area marked by red arrow. 
Also it should be responsive. 

The contributors list should contain the image and name in the same format as shown in below image. 
Also It should contain the link to that contributor's github profile.
The images should be little bit smaller than the images shown in below sscreenshot.

Make a different contributions section below ours section.
Include all the contributors there including us,

![image](https://user-images.githubusercontent.com/55577276/195523947-bb0b8c42-9b13-4d8a-8c04-1f33dde9272c.png)

**Comment by brupadhyay** [comment]
Okay, Add the "hacktoberfest" "hacktoberfest-accepted" labels to this issue and assign this to me, Contributors section should be different one or I can merge it with both of you

![image](https://user-images.githubusercontent.com/92944256/195524471-fbc861f1-c357-4959-878f-64f5c671ab20.png)

**Comment by kd1729** [comment]
@brupadhyay Yes, also I have updated the description. Please go through it,

**Comment by brupadhyay** [comment]
I'll be happy to work on this, If I have some doubts I'll ask here.

**Comment by kd1729** [comment]
> I'll be happy to work on this, If I have some doubts I'll ask here.

yeah sure. 👍🏻

**Comment by brupadhyay** [comment]
@onlykingKD assign me!!

**Comment by kd1729** [comment]
@brupadhyay A new category of Gaming just got added. So add Gaming category link in index.html, id 801 to 820.
 
https://github.com/primeTanM/Excuser/blob/f2b198ab5727d3438ecdc550444dc8533aea694c/Excuses_eng.js#L694

**Comment by brupadhyay** [comment]
Yep, @onlykingKD  please see the attachments regarding progress of contributors list
![image](https://user-images.githubusercontent.com/92944256/195678246-1c932b83-6f8c-47ac-9852-48f21e4befe0.png)
![image](https://user-images.githubusercontent.com/92944256/195678324-0bf45e79-2052-4362-91b4-b849ae4dcb3e.png)
![image](https://user-images.githubusercontent.com/92944256/195678389-cce20cdf-6537-4a9a-90cc-781aff94a4e9.png)
![image](https://user-images.githubusercontent.com/92944256/195678492-ef8fc099-3582-44d7-9c01-a1804583262f.png)
![image](https://user-images.githubusercontent.com/92944256/195678517-a856013b-d947-4df1-bfe0-edb6567ab1d5.png)

I'm about to push changes but please review this before-hand

**Comment by kd1729** [comment]
@brupadhyay yeah push it, it will not show on API until I re-deploy it on Heroku so np. I will do the minor tweaks afterwards.
Thanks a lot for these 4 contributions and improving this API.

**Comment by brupadhyay** [comment]
One humble request from myside, @onlykingKD  please add "hacktoberfest-accepted" to my all PRs till date, I'm making the PR in two!
