### ISSUE TITLE
Gaming category

### ISSUE THREAD

**Issue by ManuGil22** [primeTanM/Excuser#18]
id: 800
excuse: "Im lagging"
category: "Gaming"

id: 801
excuse: "I have stuttering"
category: "Gaming"

id: 802
excuse: "My mouse is not working"
category: "Gaming"

id: 803
excuse: "I swear i clicked!"
category: "Gaming"

id: 804
excuse: "The game ate my bullet"
category: "Gaming"

id: 805
excuse: "I was talking to my mom"
category: "Gaming"

id: 806
excuse: "My mouse is running out of battery"
category: "Gaming"

id: 807
excuse: "My internet is so bad"
category: "Gaming"

id: 808
excuse: "My joystick is not working"
category: "Gaming"

id: 809
excuse: "My joystick is running out of battery"
category: "Gaming"

id: 810
excuse: "Im not bad, im chilling"
category: "Gaming"

id: 811
excuse: "This game sound is so bad that i didnt hear they comming"
category: "Gaming"

id: 812
excuse: "They had better guns, thats why they killed me"
category: "Gaming"

id: 813
excuse: "I was flashed"
category: "Gaming"

id: 814
excuse: "I had a smoke grenade, couldt see anything"
category: "Gaming"

id: 815
excuse: "Sorry i was in the bathroom"
category: "Gaming"

id: 816
excuse: "I run out of bullets"
category: "Gaming"

id: 817
excuse: "I didnt have a gun"
category: "Gaming"

id: 818
excuse: "My headphones truend off"
category: "Gaming"

id: 819
excuse: "Im playing without sound"
category: "Gaming"

id: 820
excuse: "It was playing my brother"
category: "Gaming"

**Comment by kd1729** [comment]
@ManuGil22 Do you want to work on this issue ? if yes, please open a PR.
