### ISSUE TITLE
Issue in Contributors Section, when max-width is 500

### ISSUE THREAD

**Issue by brupadhyay** [primeTanM/Excuser#21]
![image](https://user-images.githubusercontent.com/92944256/195870305-46dd3fc1-3c18-4498-8f43-9d4ecefa636d.png)

```Below 500 the names are aligning themselves which looks not so good```
@onlykingKD

**Comment by kd1729** [comment]
@brupadhyay yeah , I changed to display:grid instead of display: flex.  Do you want to work on this issue now else I will fix it in few days ?

**Comment by pranshuj73** [comment]
would like to take this up!

**Comment by brupadhyay** [comment]
@onlykingKD ,assign me, I would like to work on this! but do you want me to work on display: grid or flex? btw It will take few days for me as well!

**Comment by kd1729** [comment]
@brupadhyay you have already completed 4 PRs.

Let @pranshuj73 work on this issue 

@pranshuj73  Make display: grid, when on big screen contributors should have 4 columns as it is now, on smaller screens 3 and on mobile screens 2.

**Comment by kd1729** [comment]
> would like to take this up!

@pranshuj73 while working on this issue, add your name also in contributors list

**Comment by brupadhyay** [comment]
Okay, what if @pranshuj73 would have completed 4? Let it be I'm going on trek tomorrow, If @pranshuj73 finishes it by the EOD tomorrow it is fine! I opened this issue for the sake of learning and implementing and Hacktoberfest is not all about 4 PRs, if I wouldn't have opened this issue then clash would not have happened.

**Comment by pranshuj73** [comment]
> Okay, what if @pranshuj73 would have completed 4? Let it be I'm going on trek tomorrow, If @pranshuj73 finishes it by the EOD tomorrow it is fine! I opened this issue for the sake of learning and implementing and Hacktoberfest is not all about 4 PRs, if I wouldn't have opened this issue then clash would not have happened.

I'm alright if you want to take the issue up, no problems brother. Just say the word. The reason I asked to be assigned was that you didn't mention that you wanted to take this up in the issue message 😅

**Comment by kd1729** [comment]
@brupadhyay It was just that @pranshuj73 hasn't contributed to this project so I told that way. You can work on it, you opened it, you have the preference anyways. 😅

**Comment by brupadhyay** [comment]
It's alright! I was a newbie before I found this repo, @pranshuj73 well you're lucky on this issue! resolve it before us(@onlykingKD and @brupadhyay ).😄

**Comment by brupadhyay** [comment]
@onlykingKD If he makes a PR by tomorrow please see to that, You first unassign me then merge his PR and close this issue.
