### ISSUE TITLE
Add a new category of Unbelievable Excuses (minimum 10) id : 601 onwards

### ISSUE THREAD

**Issue by kd1729** [primeTanM/Excuser#5]

**Comment by brupadhyay** [comment]
Assign this as well!

**Comment by kd1729** [comment]
@brupadhyay yeah ok.

**Comment by brupadhyay** [comment]
@onlykingKD Pull request has been made!

**Comment by kd1729** [comment]
@brupadhyay Thanks a lot for adding 3 differenet categories and contributing to this project.
