### ISSUE TITLE
Add a new category of Funny Excuses (minimum 10) id : 501 onwards

### ISSUE THREAD

**Issue by kd1729** [primeTanM/Excuser#6]

**Comment by brupadhyay** [comment]
Hey, @onlykingKD you may assign me this issue?

**Comment by kd1729** [comment]
@brupadhyay yeah ok go ahead !

**Comment by brupadhyay** [comment]
I have made a pull request for the same.

**Comment by kd1729** [comment]
@brupadhyay PR Merged. Thank You for the contribution!
