### ISSUE TITLE
Add a new category of Developers Excuses (minimum 10) id : 701 onwards

### ISSUE THREAD

**Issue by kd1729** [primeTanM/Excuser#7]

**Comment by brupadhyay** [comment]
@onlykingKD You may assign me this, Also I'm a beginner, Thankyou for merging my first PR😇

**Comment by kd1729** [comment]
@brupadhyay yeah go ahead add them.

**Comment by brupadhyay** [comment]
Thankyou for assigning, I will make a pull request soon.

**Comment by kd1729** [comment]
@brupadhyay thank you for this contribution also 👍

**Comment by brupadhyay** [comment]
Please close this issue as well!
