### ISSUE TITLE
API Down?

### ISSUE THREAD

**Issue by BrianYoon91** [primeTanM/Excuser#8]
Hey everyone! 

The api was working all week and it seems to be down right now? 
I was wondering if someone can look into this, I have made a project around it and was wondering when it will come back?

**Comment by kd1729** [comment]
Hi @BrianYoon91 this API works only for for first 23 days of the months as we get only 550 free hours (23 days) each month.  So this will start working from tomorrow again (1st July to 23rd July)

**Comment by kd1729** [comment]
@BrianYoon91 do you need it for all time ? I will fix it next month if you need.

**Comment by BrianYoon91** [comment]
Oh hey no worries! I will just add a note in my app! Thank you so much for the quick reply! Sorry about that!
