### ISSUE TITLE
Add a optional param request to change language of excuses

### ISSUE THREAD

**Issue by Lucas-Queiroz-Zoyo** [primeTanM/Excuser#9]

**Comment by Lucas-Queiroz-Zoyo** [comment]
@onlykingKD @cgolden15 @ianfromdover @primeTanM 
May i create a new file to translate the excuses and add a optional param to select differents languages?
Case a param is null, the default langague keeps english.

**Comment by primeTanM** [comment]
Sure, that would be great 😃

**Comment by primeTanM** [comment]
Kindly make changes into a separate branch

**Comment by zoyo23** [comment]
Can you please add me on contributor list, my push was refused. 😅

**Comment by kd1729** [comment]
> Can you please add me on contributor list, my push was refused. 😅

Which push are you talking about ?

**Comment by zoyo23** [comment]
> > Can you please add me on contributor list, my push was refused. 😅
> 
> Which push are you talking about ?

I created a branch that contains the feature with optional param. 

![image](https://user-images.githubusercontent.com/20652389/188618025-6e0a72de-562d-437d-b072-3a62d7e073fd.png)


May i push a branch to create a pull request?

@Lucas-Queiroz-Zoyo  is my alternative account, sorry about confusion.

**Comment by kd1729** [comment]
@zoyo23  Yeah sure go ahead .
